### ISSUE TITLE
can't create redis-cluster for tls

### ISSUE THREAD

**Issue by Rory-Z** [bitnami/bitnami-docker-redis-cluster#18]
**Description**

**Steps to reproduce the issue:**

I tried to create a cluster of tls using docker-compose

```
version: '3'

services:
  redis-node-0:
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:${REDIS_VSN}
    expose:
      - 6379
      - 6380
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
      - ../../apps/emqx_auth_redis/test/emqx_auth_redis_SUITE_data/certs:/opt/bitnami/redis/certs
    environment:
      - 'REDIS_PASSWORD=public'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6380
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt
    networks:
      - emqx_bridge

  redis-node-1:
    container_name: redis-node-1
    image: docker.io/bitnami/redis-cluster:${REDIS_VSN}
    expose:
      - 6379
      - 6380
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
      - ../../apps/emqx_auth_redis/test/emqx_auth_redis_SUITE_data/certs:/opt/bitnami/redis/certs
    environment:
      - 'REDIS_PASSWORD=public'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6380
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt
    networks:
      - emqx_bridge
   
  redis-node-2:
    container_name: redis-node-2
    expose:
      - 6379
      - 6380
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
      - ../../apps/emqx_auth_redis/test/emqx_auth_redis_SUITE_data/certs:/opt/bitnami/redis/certs
    image: docker.io/bitnami/redis-cluster:${REDIS_VSN}
    environment:
      - 'REDIS_PASSWORD=public'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6380
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt
    networks:
      - emqx_bridge

  redis-cluster-init:
    container_name: redis-cluster-init
    image: docker.io/bitnami/redis-cluster:${REDIS_VSN}
    volumes:
      - ../../apps/emqx_auth_redis/test/emqx_auth_redis_SUITE_data/certs:/opt/bitnami/redis/certs
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    environment:
      - 'REDISCLI_AUTH=public'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6380
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt
    networks:
      - emqx_bridge

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local

networks:
  emqx_bridge:
    driver: bridge
```

It looks like it's worked

```
$ docker logs redis-cluster-init
redis-cluster 10:52:29.89
redis-cluster 10:52:29.89 Welcome to the Bitnami redis-cluster container
redis-cluster 10:52:29.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 10:52:29.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 10:52:29.90
redis-cluster 10:52:29.90 INFO  ==> ** Starting Redis setup **
redis-cluster 10:52:29.93 INFO  ==> Initializing Redis
redis-cluster 10:52:29.94 INFO  ==> Setting Redis config file
redis-cluster 10:52:30.05 INFO  ==> ** Redis setup finished! **

Waiting 0s before querying node ip addresses
*** ERROR: Invalid configuration for cluster creation.
*** Redis Cluster requires at least 3 master nodes.
*** This is not possible with 3 nodes and 1 replicas per node.
*** At least 6 nodes are required.
The cluster was already created, the nodes should have recovered it

$ docker logs -f redis-node-2
redis-cluster 10:52:28.21
redis-cluster 10:52:28.21 Welcome to the Bitnami redis-cluster container
redis-cluster 10:52:28.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 10:52:28.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 10:52:28.22
redis-cluster 10:52:28.22 INFO  ==> ** Starting Redis setup **
redis-cluster 10:52:28.26 INFO  ==> Initializing Redis
redis-cluster 10:52:28.28 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs

redis-cluster 10:52:28.49 INFO  ==> ** Redis setup finished! **
1:C 17 Dec 2020 10:52:28.653 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Dec 2020 10:52:28.653 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Dec 2020 10:52:28.653 # Configuration loaded
1:M 17 Dec 2020 10:52:28.659 * No cluster configuration found, I'm bd00d8cd4a21ce5fe00b8b3e51f0f4b22b2bbefa
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 6.0.9 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 17 Dec 2020 10:52:28.664 # Server initialized
1:M 17 Dec 2020 10:52:28.665 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 17 Dec 2020 10:52:28.665 * Ready to accept connections
```

**Describe the results you received:**

I inserted the data using redis-cli, and it failed

```
$ docker exec -it redis-node-2 bash
I have no name!@7cf6eb225e2a:/$ redis-cli --tls --cert /opt/bitnami/redis/certs/redis.crt --key /opt/bitnami/redis/certs/redis.key --cacert /opt/bitnami/redis/certs/ca.crt -c -a public -p 6380
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6380> set foo bar
(error) CLUSTERDOWN Hash slot not served
127.0.0.1:6380> cluster info
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
```

**Version**

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)

Server:
 Containers: 12
  Running: 11
  Paused: 0
  Stopped: 1
 Images: 240
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1024-aws
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.5GiB
 Name: ip-172-31-53-38
 ID: 4WOH:WGOY:YGTK:DWP3:KRRR:U3P2:MND6:26B6:VZHG:XOUU:DYMC:L4ZM
 Docker Root Dir: /mnt/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  34.223.40.33:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):** AWS EC2
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by dani8art** [comment]
Hi @zhanghongtong 

There is a minimal number of master nodes and replicas to have it properly deployed https://redis.io/topics/cluster-tutorial

> Note that the minimal cluster that works as expected requires to contain at least three master nodes. For your first tests it is strongly suggested to start a six nodes cluster with three masters and three slaves.

In addition, you can see the error

```
Waiting 0s before querying node ip addresses
*** ERROR: Invalid configuration for cluster creation.
*** Redis Cluster requires at least 3 master nodes.
*** This is not possible with 3 nodes and 1 replicas per node.
*** At least 6 nodes are required.
The cluster was already created, the nodes should have recovered it
```

can you try to set it up with this minimum config?

Thanks!

**Comment by zhanghongtong** [comment]
Hi, @dani8art 

Thanks for your reply, I've increased the number of nodes to 6, and now they're a normal cluster.

But I have a new problem, and I'm not sure if I should innovate a new issue

I set up the docker-compose network with `enable_ipv6: true`, it looks like the cluster has failed

```
......

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.239.0/24
          gateway: 172.100.239.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
```

```
$ docker logs -f redis-cluster-init
redis-cluster 06:07:26.18
redis-cluster 06:07:26.18 Welcome to the Bitnami redis-cluster container
redis-cluster 06:07:26.18 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 06:07:26.18 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 06:07:26.18
redis-cluster 06:07:26.19 INFO  ==> ** Starting Redis setup **
redis-cluster 06:07:26.26 INFO  ==> Initializing Redis
redis-cluster 06:07:26.29 INFO  ==> Setting Redis config file
redis-cluster 06:07:26.40 INFO  ==> ** Redis setup finished! **

Waiting 0s before querying node ip addresses
Could not connect to Redis at 2001:3200:3200::0: Name or service not known
Could not connect to Redis at 2001:3200:3200::a
172.100.239.10:6380: Name or service not known
The cluster was already created, the nodes should have recovered it
```

**Comment by dani8art** [comment]
Hi @zhanghongtong ,

Currently, our assets are not 100% ready to work in ipv6 unfortunately we can not guarantee they are going to work fine on those kinds of networks.

Thanks!

**Comment by zhanghongtong** [comment]
Hi, @dani8art  

Thank you for your reply, do we have any plans to support ipv6 in the future?

**Comment by dani8art** [comment]
Yes, we are evaluating it, unfortunately, we can't give you an ETA. 

We'll keep you updated. 

Thanks!

**Comment by warrenca** [comment]
@zhanghongtong I made it work with this config. Obviously, I only used 3 master nodes.

```
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_TLS_AUTH_CLIENTS=yes'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_PORT=6379'
      - 'REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt'
    volumes:
      - ./certs:/opt/bitnami/redis/certs

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_TLS_AUTH_CLIENTS=yes'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_PORT=6379'
      - 'REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt'
    volumes:
      - ./certs:/opt/bitnami/redis/certs

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_TLS_AUTH_CLIENTS=yes'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_PORT=6379'
      - 'REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt'
    volumes:
      - ./certs:/opt/bitnami/redis/certs

#  redis-node-3:
#    image: docker.io/bitnami/redis-cluster:6.0-debian-10
#    environment:
#      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
#      - 'REDIS_PASSWORD=bitnami'
#
#  redis-node-4:
#    image: docker.io/bitnami/redis-cluster:6.0-debian-10
#    environment:
#      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
#      - 'REDIS_PASSWORD=bitnami'
#
#  redis-node-5:
#    image: docker.io/bitnami/redis-cluster:6.0-debian-10
#    environment:
#      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
#      - 'REDIS_PASSWORD=bitnami'

  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-5
    environment:
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_PORT=6379'
      - 'REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt'
    volumes:
      - ./certs:/opt/bitnami/redis/certs
```

### Log from redis-cluster-init
```
docker logs redis-cluster_redis-cluster-init_1
redis-cluster 01:04:17.99
redis-cluster 01:04:18.00 Welcome to the Bitnami redis-cluster container
redis-cluster 01:04:18.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 01:04:18.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 01:04:18.01
redis-cluster 01:04:18.01 INFO  ==> ** Starting Redis setup **
redis-cluster 01:04:18.03 INFO  ==> Initializing Redis
redis-cluster 01:04:18.05 INFO  ==> Setting Redis config file
redis-cluster 01:04:18.13 INFO  ==> ** Redis setup finished! **

Waiting 0s before querying node ip addresses
>>> Performing hash slots allocation on 3 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
M: 441ad18e1b9126b48894d1a3069c190fe8502bab 172.25.0.3:6379
   slots:[0-5460] (5461 slots) master
M: 4750de6528b06d07710306e9673a3f9688dce316 172.25.0.4:6379
   slots:[5461-10922] (5462 slots) master
M: 5e3ab1405f7eaf393bbd78c1871dc545a4a9e1b3 172.25.0.2:6379
   slots:[10923-16383] (5461 slots) master
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join
```

### A log from one of the node
```
docker logs redis-cluster_redis-node-1_1
redis-cluster 01:04:07.37
redis-cluster 01:04:07.37 Welcome to the Bitnami redis-cluster container
redis-cluster 01:04:07.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 01:04:07.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 01:04:07.38
redis-cluster 01:04:07.38 INFO  ==> ** Starting Redis setup **
redis-cluster 01:04:07.41 INFO  ==> Initializing Redis
redis-cluster 01:04:07.44 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs
redis-cluster 01:04:07.55 INFO  ==> ** Redis setup finished! **

1:C 06 Jan 2021 01:04:07.588 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Jan 2021 01:04:07.588 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 06 Jan 2021 01:04:07.588 # Configuration loaded
1:M 06 Jan 2021 01:04:07.598 * No cluster configuration found, I'm 4750de6528b06d07710306e9673a3f9688dce316
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 6.0.9 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 06 Jan 2021 01:04:07.601 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 06 Jan 2021 01:04:07.601 # Server initialized
1:M 06 Jan 2021 01:04:07.601 * Ready to accept connections
1:M 06 Jan 2021 01:04:18.391 # configEpoch set to 2 via CLUSTER SET-CONFIG-EPOCH
1:M 06 Jan 2021 01:04:18.596 # IP address for this node updated to 172.25.0.4
1:M 06 Jan 2021 01:04:23.399 # Cluster state changed: ok
```

### Setting a key value in one of the node
```
docker exec -ti redis-cluster_redis-node-1_1 bash                                                                                                                                      
I have no name!@617f4e38a8d0:/$ redis-cli --tls --cert /opt/bitnami/redis/certs/redis.crt --key /opt/bitnami/redis/certs/redis.key --cacert /opt/bitnami/redis/certs/ca.crt -c -a bitnami
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> get name
(nil)
127.0.0.1:6379> set name x
OK
127.0.0.1:6379> get name
"x"
127.0.0.1:6379> exit
I have no name!@617f4e38a8d0:/$ exit
```

### Getting the key value from another node
```
docker exec -ti redis-cluster_redis-node-0_1 bash
I have no name!@420939182eed:/$ redis-cli --tls --cert /opt/bitnami/redis/certs/redis.crt --key /opt/bitnami/redis/certs/redis.key --cacert /opt/bitnami/redis/certs/ca.crt -c -a bitnami
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> get name
-> Redirected to slot [5798] located at 172.25.0.4:6379
"x"
172.25.0.4:6379>
```

I used this Makefile to generate the certs https://nishanths.svbtle.com/setting-up-redis-with-tls, just make sure the tabs are actual table and not four spaces, otherwise you'll get an error.

```
FQDN ?= 127.0.0.1
OUTDIR ?= tls
# may be /etc/pki/tls in some machines.
# use `openssl version -a | grep OPENSSLDIR` to find out.
OPENSSLDIR ?= /etc/ssl

.PHONY: generate
generate: prepare redis.crt clean

.PHONY: prepare
prepare:
	mkdir ${OUTDIR}

.PHONY: clean
clean:
	rm -f ${OUTDIR}/openssl.cnf

openssl.cnf:
	cat ${OPENSSLDIR}/openssl.cnf > ${OUTDIR}/openssl.cnf
	echo "" >> ${OUTDIR}/openssl.cnf
	echo "[ san_env ]" >> ${OUTDIR}/openssl.cnf
	echo "subjectAltName = IP:${FQDN}" >> ${OUTDIR}/openssl.cnf

ca.key:
	openssl genrsa 4096 > ${OUTDIR}/ca.key

ca.crt: ca.key
	openssl req \
		-new \
		-x509 \
		-nodes \
		-sha256 \
		-key ${OUTDIR}/ca.key \
		-days 3650 \
		-subj "/C=AU/CN=example" \
		-out ${OUTDIR}/ca.crt

redis.csr: openssl.cnf
	# is -extensions necessary?
	# https://security.stackexchange.com/a/86999
	SAN=IP:$(FQDN) openssl req \
		-reqexts san_env \
		-extensions san_env \
		-config ${OUTDIR}/openssl.cnf \
		-newkey rsa:4096 \
		-nodes -sha256 \
		-keyout ${OUTDIR}/redis.key \
		-subj "/C=AU/CN=$(FQDN)" \
		-out ${OUTDIR}/redis.csr

redis.crt: openssl.cnf ca.key ca.crt redis.csr
	SAN=IP:$(FQDN) openssl x509 \
		-req -sha256 \
		-extfile ${OUTDIR}/openssl.cnf \
		-extensions san_env \
		-days 365 \
		-in ${OUTDIR}/redis.csr \
		-CA ${OUTDIR}/ca.crt \
		-CAkey ${OUTDIR}/ca.key \
		-CAcreateserial \
		-out ${OUTDIR}/redis.crt
```

**Comment by miguelaeh** [comment]
Hi @warrenca ,
Yes, for Ipv4 it should work as long as you provide 3 masters. The cluster configuration requires at least 3 masters, and the replication must be properly calculated. If you set for example 6 nodes you can configure replicas to 1, since you can have 3 masters and 3 slaves. But if you configure, let's say 4 nodes, that configuration will fail since it is not possible to deploy a replica per master.

**Comment by BratSinot** [comment]
@warrenca 

Greetings!

I can't understand, how you solved the problem? I have same issue, without TLS everything work fine with TLS your problem.

```yaml
version: '3'

services:
  redis-node-0:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_PASSWORD=foo
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
      - REDIS_NODES=redis-node-0

  redis-node-main:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-node-0
    environment:
      - REDIS_PASSWORD=foo
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=redis-node-0
      - REDIS_CLUSTER_CREATOR=yes
    ports:
      - "10000:6379"

```
