### ISSUE TITLE
Can i use this in docker swarm

### ISSUE THREAD

**Issue by hrydi** [bitnami/bitnami-docker-redis-cluster#2]
I'am not testing this yet, but i want to know about docker swarm with this image of redis-cluster. Is there any config to use or can't be use in docker swarm?

thank you,

**Comment by andresbono** [comment]
Hi @hrydi, we have not tested this image with Docker Swarm. What we use instead is k8s and Helm Charts: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster

**Comment by olljanat** [comment]
Yes these images works fine with Docker Swarm.

Here is example configuration:
```yaml
version: "3.4"
services:
  redis1n1:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis1n1
    networks:
      redis:
        aliases:
          - redis
          - redis-1
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==1
    volumes:
     - redis1n1-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
  redis1n2:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis1n2
    networks:
      redis:
        aliases:
          - redis
          - redis-2
    deploy:
      endpoint_mode: dnsrr    
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==2
    volumes:
     - redis1n2-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
  redis2n1:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis2n1
    networks:
      redis:
        aliases:
          - redis
          - redis-3
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==2
    volumes:
     - redis2n1-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
  redis2n2:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis2n2
    networks:
      redis:
        aliases:
          - redis
          - redis-4
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==3
    volumes:
     - redis2n2-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
  redis3n1:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis3n1
    networks:
      redis:
        aliases:
          - redis
          - redis-5
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==3
    volumes:
     - redis3n1-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
     - REDIS_PORT=7000
  redis3n2:
    image: bitnami/redis-cluster:5.0-debian-10
    hostname: redis3n2
    networks:
      redis:
        aliases:
          - redis
          - redis-6
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - engine.labels.type==worker
          - engine.labels.node==1
    volumes:
     - redis3n2-data:/bitnami/redis/data
    environment:
     - REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2
     - ALLOW_EMPTY_PASSWORD=yes
  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:5.0-debian-10
    networks:
     redis:
    deploy:
      endpoint_mode: dnsrr
      replicas: 0
    environment:
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis1n1 redis1n2 redis2n1 redis2n2 redis3n1 redis3n2'
      - 'REDIS_CLUSTER_CREATOR=yes'

networks:
    redis:
        external: true
volumes:
  redis1n1-data:
    name: redis1n1
    driver: local
  redis1n2-data:
    name: redis1n2
    driver: local
  redis2n1-data:
    name: redis2n1
    driver: local
  redis2n2-data:
    name: redis2n2
    driver: local
  redis3n1-data:
    name: redis3n1
    driver: local
  redis3n2-data:
    name: redis3n2
    driver: local
```
When you want init new cluster just scale up "redis-cluster-init" to 1 and after init is done back to 0.

Tricky part is that how you make sure that different shards master+slave pair are really scheduled to running top of different servers as other why cluster does not survive from server failure.
You can read more about that dilemma from https://alex.dzyoba.com/blog/redis-cluster/ but as you can see on my example we use Docker engine label to pin point specific container to specific node and use those n1 and n2 names for each shard but you still to manually check that correct containers are creating those pairs.

And everytime failover happens (because of server reboot, etc) you need manually failover those back to correct places (or create some automation for it).

But afaiu there those are generic Redis Cluster issues/limitation which are not handled even by Bitnami Helm Chart so from that point of view same functionality is available with both Swarm and K8s using these images.

**Comment by andresbono** [comment]
Hi @olljanat, thank you very much for sharing your Docker Swarm setup in this issue!! 💯

**Comment by hrydi** [comment]
thank you mr. @olljanat  for your example Docker Swarm setup. 
kinda busy for testing your setup this time, maybe later i'll try it.

**Comment by skjnldsv** [comment]
Here is my example taking advantage of deploy parametters

```yml
version: '3.7'
services:
  workers:
    image: docker.io/bitnami/redis-cluster:6.2
    hostname: node{{.Task.Slot}}
    networks:
      - redis
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=node0'

    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        window: 30s

  manager:
    image: docker.io/bitnami/redis-cluster:6.2
    hostname: node0
    networks:
      - redis
    depends_on:
      - workers
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=node0 node1 node2 node3 node4 node5'
      - 'REDIS_CLUSTER_CREATOR=yes'

networks:
  redis:
    driver: overlay
```

Unfortunately, you cannot take advantage of service scaling as adding new nodes will not work. I don't thing this is supported by the `bitnami-docker-redis-cluster` service
