### ISSUE TITLE
Bug with cluster-init and different ports with redis 6.2.2 image

### ISSUE THREAD

**Issue by Elyytscha** [bitnami/bitnami-docker-redis-cluster#25]
**Description**

with the redis-cluster image version: 6.2.1 it was possible to configure a 6 node M/S setup on 3 Hosts, with the image 6.2.2 this isn't working anymore

**Steps to reproduce the issue:**

Working
docker-compose.yml
```
...
  docker-redis-cluster-init:                                                                                                                                                                                                                  
    image: 'bitnami/redis-cluster:6.2.1'                                                                                                                                                                                     
    depends_on:                                                                                                                                                                                                                               
      - docker-redis                                                                                                                                                                                                                          
    #restart: always
    #env_file: ${ENVIRONMENT:-service.env}
    environment:
      - 'REDISCLI_AUTH=password'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_NODES=redis1.example.com redis2.example.com redis3.example.com redis1.example.com:6380 redis2.example.com:6380 redis3.example.com:6380'
      - 'REDIS_PASSWORD=password'
      - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10'
...
```
output:
```
redis-cluster 15:49:35.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 15:49:35.40 
redis-cluster 15:49:35.40 INFO  ==> ** Starting Redis setup **
redis-cluster 15:49:35.44 INFO  ==> Initializing Redis
redis-cluster 15:49:35.46 INFO  ==> Setting Redis config file
redis-cluster 15:49:35.53 INFO  ==> ** Redis setup finished! **

Waiting 10s before querying node ip addresses
>>> Performing hash slots allocation on 6 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
Adding replica 10.197.0.36:6380 to 10.197.0.35:6379
Adding replica 10.197.0.39:6380 to 10.197.0.36:6379
Adding replica 10.197.0.35:6380 to 10.197.0.39:6379
M: 771b1666048ccac0b67d3efe1b6053b4f88d3bc7 10.197.0.35:6379
   slots:[0-5460] (5461 slots) master
M: 4e593be84559b9cf14e56c90412a8b27db644c60 10.197.0.36:6379
   slots:[5461-10922] (5462 slots) master
M: 2466c806738b847a2ec9d39bd8bfc7911e259990 10.197.0.39:6379
   slots:[10923-16383] (5461 slots) master
S: 7c5cf0a829defcda2edca86a33824e16f4ec0d7d 10.197.0.35:6380
   replicates 2466c806738b847a2ec9d39bd8bfc7911e259990
S: 1ecad54d294530c209c12aa04e528a239ad60fb4 10.197.0.36:6380
   replicates 771b1666048ccac0b67d3efe1b6053b4f88d3bc7
S: 8e7b7fedd8b18ddb0be84c1ec61a498fcd774c2c 10.197.0.39:6380
   replicates 4e593be84559b9cf14e56c90412a8b27db644c60
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join

>>> Performing Cluster Check (using node 10.197.0.35:6379)
M: 771b1666048ccac0b67d3efe1b6053b4f88d3bc7 10.197.0.35:6379
   slots:[0-5460] (5461 slots) master
   1 additional replica(s)
S: 1ecad54d294530c209c12aa04e528a239ad60fb4 10.197.0.36:6380
   slots: (0 slots) slave
   replicates 771b1666048ccac0b67d3efe1b6053b4f88d3bc7
S: 8e7b7fedd8b18ddb0be84c1ec61a498fcd774c2c 10.197.0.39:6380
   slots: (0 slots) slave
   replicates 4e593be84559b9cf14e56c90412a8b27db644c60
M: 2466c806738b847a2ec9d39bd8bfc7911e259990 10.197.0.39:6379
   slots:[10923-16383] (5461 slots) master
   1 additional replica(s)
S: 7c5cf0a829defcda2edca86a33824e16f4ec0d7d 10.197.0.35:6380
   slots: (0 slots) slave
   replicates 2466c806738b847a2ec9d39bd8bfc7911e259990
M: 4e593be84559b9cf14e56c90412a8b27db644c60 10.197.0.36:6379
   slots:[5461-10922] (5462 slots) master
   1 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
Cluster correctly created
```

Failing:
docker-compose.yml
```
...
  docker-redis-cluster-init:                                                                                                                                                                                                                  
    image: 'bitnami/redis-cluster:6.2.2'                                                                                                                                                                                     
    depends_on:                                                                                                                                                                                                                               
      - docker-redis                                                                                                                                                                                                                          
    #restart: always
    #env_file: ${ENVIRONMENT:-service.env}
    environment:
      - 'REDISCLI_AUTH=password'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_NODES=redis1.example.com redis2.example.com redis3.example.com redis1.example.com:6380 redis2.example.com:6380 redis3.example.com:6380'
      - 'REDIS_PASSWORD=password'
      - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10'
...
```
output:
```
redis-cluster 15:52:55.37 
redis-cluster 15:52:55.37 Welcome to the Bitnami redis-cluster container
redis-cluster 15:52:55.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 15:52:55.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 15:52:55.38 
redis-cluster 15:52:55.38 INFO  ==> ** Starting Redis setup **
redis-cluster 15:52:55.42 INFO  ==> Initializing Redis
redis-cluster 15:52:55.44 INFO  ==> Setting Redis config file
```



**Describe the results you received:**

cluster does not initialize with image 6.2.2

**Describe the results you expected:**

a successfull init with image 6.2.2

**Additional information you deem important (e.g. issue happens only occasionally):**

My Workaround:

use 6.2.2 for cluster nodes as image
use 6.2.1 for cluster init node as image


**Version**

redis-cluster 6.2.2
