### ISSUE TITLE
Redis cluster down time on kubernetes when delete any pod

### ISSUE THREAD

**Issue by itleets** [bitnami/bitnami-docker-redis-cluster#35]
**Description**
I have deployed redis-cluster from here:
`https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster`

Using following command:
`helm install redis-cluster bitnami/redis-cluster --create-namespace -n redis -f redis-values.yaml`

and `redis-values-yaml` is:

```
cluster:
  init: true
  nodes: 6
  replicas: 1

password: "redis@pass"

redis:
  configmap: |-
    maxmemory 600mb
    maxmemory-policy allkeys-lru
    maxclients 40000

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
```
I'm connecting with following host: `redis://redis-cluster-headless.redis.svc.cluster.local:6379`
Which is working fine but when i remove any pod from redis deploy then i start getting error
`java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster`
Until all pods started
I also tried to pass all pods of redis to host like this:
`redis://redis-cluster-0.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-1.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-2.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-3.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-4.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-5.redis-cluster-headless.redis.svc.cluster.local:6379`

But still same issue
**Describe the results you expected:**

It should not give any error until all pods down.

**Version**

Kubernetes 1.21.5
