### ISSUE TITLE
Redis-cluster not starting in kube

### ISSUE THREAD

**Issue by crrazyman** [bitnami/bitnami-docker-redis-cluster#36]
**Description**

Hello. I'm trying to deploy redis-cluster in kubernetes (Azure AKS) and none of the pods start because:

```
Dmanea-m:azure dmanea$ kubectl -n cluster-stage logs pod/redis-cluster-0
redis-cluster 20:09:53.17 
redis-cluster 20:09:53.18 Welcome to the Bitnami redis-cluster container
redis-cluster 20:09:53.18 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 20:09:53.18 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 20:09:53.18 
redis-cluster 20:09:53.18 INFO  ==> ** Starting Redis setup **
redis-cluster 20:09:53.21 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-cluster 20:09:53.22 INFO  ==> Initializing Redis
mkdir: cannot create directory '/opt/bitnami/redis/tmp': Permission denied
```

**Steps to reproduce the issue:**

Deploy redis-cluster as a statefulset:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: cluster-stage
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: redis
        image: bitnami/redis-cluster:6.2
        ports:
        - containerPort: 6379
          name: redis-port
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_CLUSTER_REPLICAS
          value: "1"
        - name: REDIS_NODES
          value: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
        volumeMounts:
        - name: data-volume
          mountPath: /bitnami
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      storageClassName: managed-premium
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
```

**Describe the results you received:**

```
Dmanea-m:azure dmanea$ kubectl -n cluster-stage get pod,svc,pvc
NAME                                                READY   STATUS             RESTARTS   AGE
pod/redis-cluster-0                                 0/1     CrashLoopBackOff   1          28s
```

**Describe the results you expected:**

All the pods (6 of them) should be 1/1 Running

**Version**

- Output of `docker version`:

```
kube version v1.20.9
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Azure AKS
