### ISSUE TITLE
Running this docker-compose file in "Fedora 35" always fails

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [bitnami/bitnami-docker-redis-cluster#39]
### Name and Version

docker.io/bitnami/redis-cluster:latest

### What steps will reproduce the bug?

1. See "Additional information" for details. 
2. See "Additional information" for details. 
3. See "What do you see instead?" for details. 
4. See "What do you see instead?" for details. 

other:
Occasionally this configuration file works, and sometimes it doesn't. (https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml)

### What is the expected behavior?

Identify where the problem is and hope for a solution.

### What do you see instead?

"docker-compose.yaml" running log:
```log
Attaching to Redis-2, Redis-1, Redis-0, Redis-4, Redis-3, Redis-5
Redis-1    | redis-cluster 03:16:17.93
Redis-0    | redis-cluster 03:16:17.98
Redis-1    | redis-cluster 03:16:17.93 Welcome to the Bitnami redis-cluster container
Redis-2    | redis-cluster 03:16:17.84
Redis-2    | redis-cluster 03:16:17.84 Welcome to the Bitnami redis-cluster container
Redis-0    | redis-cluster 03:16:17.99 Welcome to the Bitnami redis-cluster container
Redis-1    | redis-cluster 03:16:17.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-3    | redis-cluster 03:16:18.33
Redis-4    | redis-cluster 03:16:18.15
Redis-2    | redis-cluster 03:16:17.85 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-1    | redis-cluster 03:16:17.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-4    | redis-cluster 03:16:18.16 Welcome to the Bitnami redis-cluster container
Redis-1    | redis-cluster 03:16:17.95
Redis-3    | redis-cluster 03:16:18.34 Welcome to the Bitnami redis-cluster container
Redis-0    | redis-cluster 03:16:17.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-1    | redis-cluster 03:16:17.96 INFO  ==> ** Starting Redis setup **
Redis-4    | redis-cluster 03:16:18.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-1    | redis-cluster 03:16:18.02 INFO  ==> Initializing Redis
Redis-2    | redis-cluster 03:16:17.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-0    | redis-cluster 03:16:18.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-4    | redis-cluster 03:16:18.17 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-3    | redis-cluster 03:16:18.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-3    | redis-cluster 03:16:18.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-5    | redis-cluster 03:16:19.52
Redis-0    | redis-cluster 03:16:18.00
Redis-3    | redis-cluster 03:16:18.35
Redis-1    | redis-cluster 03:16:18.07 INFO  ==> Setting Redis config file
Redis-0    | redis-cluster 03:16:18.01 INFO  ==> ** Starting Redis setup **
Redis-3    | redis-cluster 03:16:18.36 INFO  ==> ** Starting Redis setup **
Redis-5    | redis-cluster 03:16:19.52 Welcome to the Bitnami redis-cluster container
Redis-4    | redis-cluster 03:16:18.17
Redis-5    | redis-cluster 03:16:19.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
Redis-2    | redis-cluster 03:16:17.86
Redis-2    | redis-cluster 03:16:17.87 INFO  ==> ** Starting Redis setup **
Redis-4    | redis-cluster 03:16:18.18 INFO  ==> ** Starting Redis setup **
Redis-3    | redis-cluster 03:16:18.43 INFO  ==> Initializing Redis
Redis-0    | redis-cluster 03:16:18.08 INFO  ==> Initializing Redis
Redis-5    | redis-cluster 03:16:19.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
Redis-4    | redis-cluster 03:16:18.24 INFO  ==> Initializing Redis
Redis-2    | redis-cluster 03:16:17.94 INFO  ==> Initializing Redis
Redis-4    | redis-cluster 03:16:18.30 INFO  ==> Setting Redis config file
Redis-5    | redis-cluster 03:16:19.54
Redis-0    | redis-cluster 03:16:18.13 INFO  ==> Setting Redis config file
Redis-2    | redis-cluster 03:16:18.00 INFO  ==> Setting Redis config file
Redis-5    | redis-cluster 03:16:19.54 INFO  ==> ** Starting Redis setup **
Redis-3    | redis-cluster 03:16:18.47 INFO  ==> Setting Redis config file
Redis-3    | Storing map with hostnames and IPs
Redis-3    |
Redis-3    | redis-cluster 03:16:18.72 INFO  ==> ** Redis setup finished! **
Redis-4    | Storing map with hostnames and IPs
Redis-3    | 1:C 26 Mar 2022 03:16:18.793 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-3    | 1:C 26 Mar 2022 03:16:18.793 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
Redis-3    | 1:C 26 Mar 2022 03:16:18.793 # Configuration loaded
Redis-4    | redis-cluster 03:16:18.56 INFO  ==> ** Redis setup finished! **
Redis-4    |
Redis-3    | 1:M 26 Mar 2022 03:16:18.794 * monotonic clock: POSIX clock_gettime
Redis-3    | 1:M 26 Mar 2022 03:16:18.795 * No cluster configuration found, I'm 0c7e98a1850accfd739f5fde1a3a9b93b4f5cbea
Redis-3    | 1:M 26 Mar 2022 03:16:18.798 * Running mode=cluster, port=6379.
Redis-3    | 1:M 26 Mar 2022 03:16:18.798 # Server initialized
Redis-3    | 1:M 26 Mar 2022 03:16:18.798 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-4    | 1:C 26 Mar 2022 03:16:18.654 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-4    | 1:C 26 Mar 2022 03:16:18.654 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
Redis-4    | 1:C 26 Mar 2022 03:16:18.654 # Configuration loaded
Redis-3    | 1:M 26 Mar 2022 03:16:18.799 * Ready to accept connections
Redis-4    | 1:M 26 Mar 2022 03:16:18.655 * monotonic clock: POSIX clock_gettime
Redis-4    | 1:M 26 Mar 2022 03:16:18.657 * No cluster configuration found, I'm 9739a9bf0e566ced472e6bc161d855660b263123
Redis-4    | 1:M 26 Mar 2022 03:16:18.660 * Running mode=cluster, port=6379.
Redis-4    | 1:M 26 Mar 2022 03:16:18.660 # Server initialized
Redis-4    | 1:M 26 Mar 2022 03:16:18.660 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-4    | 1:M 26 Mar 2022 03:16:18.662 * Ready to accept connections
Redis-5    | redis-cluster 03:16:19.60 INFO  ==> Initializing Redis
Redis-5    | redis-cluster 03:16:19.63 INFO  ==> Setting Redis config file
Redis-5    | Storing map with hostnames and IPs
Redis-5    | redis-cluster 03:16:19.81 INFO  ==> ** Redis setup finished! **
Redis-5    |
Redis-5    | 95:C 26 Mar 2022 03:16:19.880 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-5    | 95:C 26 Mar 2022 03:16:19.880 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=95, just started
Redis-5    | 95:C 26 Mar 2022 03:16:19.880 # Configuration loaded
Redis-5    | 95:M 26 Mar 2022 03:16:19.881 * monotonic clock: POSIX clock_gettime
Redis-5    | 95:M 26 Mar 2022 03:16:19.882 * No cluster configuration found, I'm e1026607cf3a5c8869f5fadcf0db95959531b842
Redis-5    | Could not connect to Redis at Redis-0:6379: Connection refused
Redis-5    | Node Redis-0 not ready, waiting for all the nodes to be ready...
Redis-5    | 95:M 26 Mar 2022 03:16:19.888 * Running mode=cluster, port=6379.
Redis-5    | 95:M 26 Mar 2022 03:16:19.888 # Server initialized
Redis-5    | 95:M 26 Mar 2022 03:16:19.888 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-5    | 95:M 26 Mar 2022 03:16:19.890 * Ready to accept connections
Redis-5    | Could not connect to Redis at Redis-0:6379: Connection refused
Redis-5    | Node Redis-0 not ready, waiting for all the nodes to be ready...
Redis-5    | Could not connect to Redis at Redis-0:6379: Connection refused
Redis-5    | Node Redis-0 not ready, waiting for all the nodes to be ready...
Redis-5    | Could not connect to Redis at Redis-0:6379: Connection refused
Redis-5    | Node Redis-0 not ready, waiting for all the nodes to be ready...
Redis-2    | Storing map with hostnames and IPs
Redis-2    |
Redis-2    | redis-cluster 03:16:23.30 INFO  ==> ** Redis setup finished! **
Redis-1    | Storing map with hostnames and IPs
Redis-1    |
Redis-1    | redis-cluster 03:16:23.35 INFO  ==> ** Redis setup finished! **
Redis-2    | 1:C 26 Mar 2022 03:16:23.385 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-2    | 1:C 26 Mar 2022 03:16:23.385 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
Redis-2    | 1:C 26 Mar 2022 03:16:23.385 # Configuration loaded
Redis-2    | 1:M 26 Mar 2022 03:16:23.386 * monotonic clock: POSIX clock_gettime
Redis-2    | 1:M 26 Mar 2022 03:16:23.388 * No cluster configuration found, I'm 823139389dd6384626ca16d01b48b88b3c8a91de
Redis-0    | Storing map with hostnames and IPs
Redis-2    | 1:M 26 Mar 2022 03:16:23.396 * Running mode=cluster, port=6379.
Redis-2    | 1:M 26 Mar 2022 03:16:23.396 # Server initialized
Redis-2    | 1:M 26 Mar 2022 03:16:23.396 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-2    | 1:M 26 Mar 2022 03:16:23.398 * Ready to accept connections
Redis-0    | redis-cluster 03:16:23.40 INFO  ==> ** Redis setup finished! **
Redis-0    |
Redis-1    | 1:C 26 Mar 2022 03:16:23.443 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-1    | 1:C 26 Mar 2022 03:16:23.443 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
Redis-1    | 1:C 26 Mar 2022 03:16:23.443 # Configuration loaded
Redis-1    | 1:M 26 Mar 2022 03:16:23.444 * monotonic clock: POSIX clock_gettime
Redis-1    | 1:M 26 Mar 2022 03:16:23.445 * No cluster configuration found, I'm 253500f36359a03bd471ded48fc5798168af21bb
Redis-1    | 1:M 26 Mar 2022 03:16:23.448 * Running mode=cluster, port=6379.
Redis-1    | 1:M 26 Mar 2022 03:16:23.449 # Server initialized
Redis-1    | 1:M 26 Mar 2022 03:16:23.449 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-1    | 1:M 26 Mar 2022 03:16:23.450 * Ready to accept connections
Redis-0    | 1:C 26 Mar 2022 03:16:23.479 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Redis-0    | 1:C 26 Mar 2022 03:16:23.479 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
Redis-0    | 1:C 26 Mar 2022 03:16:23.479 # Configuration loaded
Redis-0    | 1:M 26 Mar 2022 03:16:23.480 * monotonic clock: POSIX clock_gettime
Redis-0    | 1:M 26 Mar 2022 03:16:23.482 * No cluster configuration found, I'm 2609df15b89d800db5f9b04d854cbbb86802f60f
Redis-0    | 1:M 26 Mar 2022 03:16:23.485 * Running mode=cluster, port=6379.
Redis-0    | 1:M 26 Mar 2022 03:16:23.486 # Server initialized
Redis-0    | 1:M 26 Mar 2022 03:16:23.486 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Redis-0    | 1:M 26 Mar 2022 03:16:23.487 * Ready to accept connections
Redis-5    | Waiting 0s before querying node ip addresses
Redis-5    | *** ERROR: Invalid configuration for cluster creation.
Redis-5    | *** Redis Cluster requires at least 3 master nodes.
Redis-5    | *** This is not possible with 6 nodes and 3 replicas per node.
Redis-5    | *** At least 12 nodes are required.
Redis-5    | The cluster was already created, the nodes should have recovered it
Redis-5    | redis-server "${ARGS[@]}"
```
-----------------------
error info:
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0

-----------------------

### Additional information
```yaml
docker-compose.yaml:
version: "3.7"
services:
  Redis-0:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-0
    ports:
      - 6380:6379
    volumes:
      - REDIS-0-Data:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
    networks:
      NETWORK:
        aliases:
          - Redis-0

  Redis-1:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-1
    ports:
      - 6381:6379
    volumes:
      - REDIS-1-Data:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
    networks:
      NETWORK:
        aliases:
          - Redis-1

  Redis-2:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-2
    ports:
      - 6382:6379
    volumes:
      - REDIS-2-Data:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
    networks:
      NETWORK:
        aliases:
          - Redis-2

  Redis-3:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-3
    ports:
      - 6383:6379
    volumes:
      - REDIS-3-Data:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
    networks:
      NETWORK:
        aliases:
          - Redis-3

  Redis-4:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-4
    ports:
      - 6384:6379
    volumes:
      - REDIS-4-Data:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
    networks:
      NETWORK:
        aliases:
          - Redis-4

  Redis-5:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: Redis-5
    ports:
      - 6385:6379
    volumes:
      - REDIS-5-Data:/bitnami/redis/data
    depends_on:
      - Redis-0
      - Redis-1
      - Redis-2
      - Redis-3
      - Redis-4
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDISCLI_AUTH=bitnami"
      - "REDIS_CLUSTER_REPLICAS=3"
      - "REDIS_NODES=Redis-0 Redis-1 Redis-2 Redis-3 Redis-4 Redis-5"
      - "REDIS_CLUSTER_CREATOR=yes"
    networks:
      NETWORK:
        aliases:
          - Redis-5

networks:
  NETWORK:
    name: NETWORK

volumes:
  REDIS-0-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-0-Data/
  REDIS-1-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-1-Data/
  REDIS-2-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-2-Data/
  REDIS-3-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-3-Data/
  REDIS-4-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-4-Data/
  REDIS-5-Data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./REDIS-5-Data/
```
