### ISSUE TITLE
Cannot connect to cluster using lettuce

### ISSUE THREAD

**Issue by ash-sykes-acn** [bitnami/bitnami-docker-redis-cluster#49]
### Name and Version

bitnami/redis-cluster:6.2-debian-10

### What steps will reproduce the bug?

Create a cluster using the following docker-compose:
```yml
services:
  redis-node:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10
    ports:
      - '7000:6379'
      - '6379:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node'
      - 'REDIS_PASSWORD=master'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=localhost'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=7000'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
```
Create the client connection using lettuce
```java
        final RedisURI redisUri = RedisURI.Builder.redis(hostName, Integer.parseInt(port)).withPassword("master").build();
        final RedisClusterClient redisClusterClient = RedisClusterClient.create(redisUri);
        final ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .dynamicRefreshSources(false)
                .build();
        redisClusterClient.setOptions(ClusterClientOptions.builder().topologyRefreshOptions(topologyRefreshOptions).build());
        return redisClusterClient;
```
Attempt to use the connection to persist data
```java
    public Optional<String> setString(final String key) {
        try (StatefulRedisClusterConnection<String, String> connection = redisClusterClient.connect()) {
            final RedisAdvancedClusterCommands<String, String> syncCommands = connection.sync();
            log.debug("MemoryDbCacheRepository setString() called..");
            syncCommands.set(key, "testing");
            final String res = syncCommands.get(key);
            log.info("Res {}", res);
            return Optional.of(res);
        } catch (Exception e) {
            log.error("Failed to set string", e);
            return Optional.empty();
        }
    }
```

### What is the expected behavior?

Client should connect and persist data

### What do you see instead?

Error where the connection doesn't have any slots:
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/102745785/174568748-43c91149-d610-4604-b371-8ef4e2260e90.png">
Resulting in an error `io.lettuce.core.cluster.PartitionSelectorException: Cannot determine a partition for slot 6918.`

### Additional information

Not sure if this is the appropriate place. I've tried to slim down the compose to not create as many nodes as I always get this error regardless of cluster size. Posting here first as the above works if I use https://github.com/Grokzen/docker-redis-cluster but that doesn't support setting `cluster_annouce_ip`
