### ISSUE TITLE
can't create redis-cluster 

### ISSUE THREAD

**Issue by Pin-Cheng** [bitnami/bitnami-docker-redis-cluster#6]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
```
docker-compose up -d
```
2. [Second Step]
```
docker exec -it redis-cluster-init sh 
```
3. [and so on...]
```
redis-cli -h redis-node-0 -p 7000 cluster info
```

**Describe the results you received:**

i need create redis-cluster (port 7000:7005)on docker-compose,now is create ,but i get some error ,and redis clusetr info status is "fail"
```
redis-node-0:7000> cluster info
cluster_state:fail
cluster_slots_assigned:5461
cluster_slots_ok:5461
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:1
cluster_current_epoch:1
cluster_my_epoch:1
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - '7000:7000'
    environment:
      - 'REDIS_PORT=7000'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - '7001:7001'
    environment:
      - 'REDIS_PORT=7001'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    ports:
      - '7002:7002'
    environment:
      - 'REDIS_PORT=7002'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    ports:
      - '7003:7003'
    environment:
      - 'REDIS_PORT=7003'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    ports:
      - '7004:7004'
    environment:
      - 'REDIS_PORT=7004'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    ports:
      - '7005:7005'
    environment:
      - 'REDIS_PORT=7005'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      #- 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      #- 'REDISCLI_AUTH=bitnami'
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
