### ISSUE TITLE
Can't use redis-cluster using docker-compose 

### ISSUE THREAD

**Issue by hjiwoo-tc** [bitnami/bitnami-docker-redis-cluster#7]
**Description**

Using the docker-compose the cluster is created fine, but after mapping ports and when I connect to it, the nodes don't redirect properly.

To try to fix this I used the redis.conf settings: `cluster-announce-port`, `cluster-announce-ip`, `cluster-announce-bus` and appended these args to `$ARGS` in run.sh. Below you can see what values I set for these settings in my docker-compose.yml

After these 'fixes' the cluster creation hangs on "waiting for the cluster to join".

**docker-compose.yml**
Note: "bitnami-test" is the same bitnami (6.0) image but with the changes made to run.sh

```
version: '2'
services:
  redis-node-0:
    image: bitnami-test
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8000'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18000'
    ports:
      - '8000:6379'
      - '18000:16379'

  redis-node-1:
    image: bitnami-test
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8001'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18001'
    ports:
      - '8001:6379'
      - '18001:16379'

  redis-node-2:
    image: bitnami-test
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8002'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18002'
    ports:
      - '8002:6379'
      - '18002:16379'

  redis-node-3:
    image: bitnami-test
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8003'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18003'
    ports:
      - '8003:6379'
      - '18003:16379'

  redis-node-4:
    image: bitnami-test
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8004'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18004'
    ports:
      - '8004:6379'
      - '18004:16379'

  redis-node-5:
    image: bitnami-test
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'CLUSTER_ANNOUNCE_PORT=8005'
      - 'CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'CLUSTER_ANNOUNCE_BUS=18005'
    ports:
      - '8005:6379'
      - '18005:16379'

  redis-cluster-init:
    image: bitnami-test
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
```

**run.sh**
```
#!/bin/bash

# shellcheck disable=SC1091
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace

# Load libraries
. /opt/bitnami/scripts/libos.sh
. /opt/bitnami/scripts/librediscluster.sh

# Load Redis environment variables
eval "$(redis_cluster_env)"

IFS=' ' read -ra nodes <<< "$REDIS_NODES"

if ! is_boolean_yes "$REDIS_CLUSTER_CREATOR"; then

  # Constants
  EXEC=$(command -v redis-server)

  ARGS=("--port" "$REDIS_PORT")
  ARGS+=("--cluster-announce-port" "$CLUSTER_ANNOUNCE_PORT")
  ARGS+=("--cluster-announce-ip" "$CLUSTER_ANNOUNCE_IP")
  ARGS+=("--cluster-announce-bus-port" "$CLUSTER_ANNOUNCE_BUS")
  ARGS+=("--include" "${REDIS_BASEDIR}/etc/redis.conf")

  if ! is_boolean_yes "$ALLOW_EMPTY_PASSWORD"; then
    ARGS+=("--requirepass" "$REDIS_PASSWORD")
    ARGS+=("--masterauth" "$REDIS_PASSWORD")
  else
    ARGS+=("--protected-mode" "no")
  fi

  info "${ARGS[@]}"

  if am_i_root; then
      exec gosu "$REDIS_DAEMON_USER" "$EXEC" "${ARGS[@]}"
  else
      exec "$EXEC" "${ARGS[@]}"
  fi

else
  redis_cluster_create "${nodes[@]}"
fi
```

**Steps to reproduce the issue:**

1. Copy my changes to docker-compose.yml and run.sh
2. run `docker-compose up`

**Describe the results you received:**

Cluster creator docker image hangs on "waiting for the cluster to join" indefinitely.

**Describe the results you expected:**

Cluster to be created

**Additional information you deem important (e.g. issue happens only occasionally):**

I figure it must have to do with the bus ports, but I have no idea what.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community 
  Version:           19.03.8                                    
  API version:       1.40                                                                  
  Go version:        go1.12.17                                                             
  Git commit:        afacb8b7f0                                                           
  Built:             Wed Mar 11 01:25:46 2020                                              
  OS/Arch:           linux/amd64                                                           
  Experimental:      false               
                                                                                                                                          
Server: Docker Engine - Community                                                         
  Engine:                                                                                   
     Version:           19.03.8                                                                
    API version:      1.40 (minimum version 1.12)                                            
    Go version:       go1.12.17                                                              
    Git commit:      afacb8b                                                                
    Built:                Wed Mar 11 01:29:16 2020                                               
    OS/Arch:          linux/amd64                                                            
    Experimental:   false                                                                 
  containerd:                                                                               
    Version:          v1.2.13                                                                
    GitCommit:     7ad184331fa3e55e52b890ea95e65ba581ae3429                              
  runc:                                                                                     
    Version:          1.0.0-rc10                                                             
    GitCommit:     dc9208a3303feef5b3839f4323d9beb36df0a9dd                              
  docker-init:                                                                             
    Version:          0.18.0                                                                 
    GitCommit:    fec3683 
```

- Output of `docker info`:

```Client:
  Debug Mode: false

Server:
  Containers: 178
    Running: 6
    Paused: 0
    Stopped: 172
  Images: 914
  Server Version: 19.03.8
  Storage Driver: overlay2
    Backing Filesystem: <unknown>
    Supports d_type: true
    Native Overlay Diff: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Swarm: inactive
  Runtimes: runc
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
  runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
  init version: fec3683
  Security Options:
    seccomp
      Profile: default
  Kernel Version: 4.19.104-microsoft-standard
  Operating System: Docker Desktop
  OSType: linux
  Architecture: x86_64
  CPUs: 8
  Total Memory: 12.28GiB
  Name: docker-desktop
  ID: DZJ2:EF7W:4XT3:7CGX:4MEZ:AITY:R2Z4:Z3AV:IIZB:DNH3:TG4Q:MOH7
  Docker Root Dir: /var/lib/docker
  Debug Mode: true
    File Descriptors: 88
    Goroutines: 88
    System Time: 2020-07-23T18:30:36.8136292Z
    EventsListeners: 3
  Registry: https://index.docker.io/v1/
  Labels:
  Experimental: false
  Insecure Registries:
    127.0.0.0/8
  Live Restore Enabled: false 
  Product License: Community Engine 


WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
WSL 2; Ubuntu 18.04
